contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/ptarmiganlabs/qs-util/discussions/new
    about: Share ideas for new features
  - name: â“ Question
    url: https://github.com/ptarmiganlabs/qs-util/discussions/new
    about: General questions
  - name: ğŸª² Bug report
    url: https://github.com/ptarmiganlabs/qs-util/issues/new
    about: Something isn't working?
